# This is served as a docker config. After editing run:
#
# $ docker stack rm monitoring
# $ DOMAIN=example.com docker stack deploy -c monitoring.yaml monitoring

global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: node
    static_configs:
      - targets: ["manager-01:9100", "manager-02:9100", "manager-03:9100"]
  - job_name: grafana
    static_configs:
      - targets: ["grafana:3000"]
