---
- hosts: all
  become: true

  name: Install CEPH
  tasks:
    - name: Add CEPH $basearch repository
      ansible.builtin.yum_repository:
        name: ceph
        description: Ceph $basearch
        baseurl: https://download.ceph.com/rpm-quincy/el8/$basearch
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add CEPH noarch repository
      ansible.builtin.yum_repository:
        name: ceph-noarch
        description: Ceph noarch
        baseurl: https://download.ceph.com/rpm-quincy/el8/noarch
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add CEPH source repository
      ansible.builtin.yum_repository:
        name: ceph-source
        description: Ceph SRPMS
        baseurl: https://download.ceph.com/rpm-quincy/el8/SRPMS
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add EPEL repository
      ansible.builtin.dnf:
        name:
          - epel-release
        state: present

    - name: Install cephadm and ceph-common
      ansible.builtin.dnf:
        name:
          - cephadm
          - ceph-common
        state: present

    - name: Disable ceph traffic in default zone
      ansible.posix.firewalld:
        service: ceph
        permanent: true
        state: disabled
        immediate: true

    - name: Disable ceph-mon traffic in default zone
      ansible.posix.firewalld:
        service: ceph-mon
        permanent: true
        state: disabled
        immediate: true

    - name: Disable 9283/tcp traffic in default zone
      ansible.posix.firewalld:
        port: 9283/tcp
        permanent: true
        state: disabled
        immediate: true

    - name: Get ceph.pub contents
      ansible.builtin.shell: cat /etc/ceph/ceph.pub
      register: ceph_pub
      delegate_to: manager-01
      run_once: true

    - name: Distribute ceph.pub to hosts
      ansible.builtin.lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: "{{ ceph_pub.stdout }}"

    - name: Add manager-02 to the cluster
      shell: ceph orch host add manager-02 10.0.0.2 --labels _admin
      delegate_to: manager-01
      run_once: true

    - name: Add manager-03 to the cluster
      shell: ceph orch host add manager-03 10.0.0.3 --labels _admin
      delegate_to: manager-01
      run_once: true

    - name: Add all available disks to the cluster
      shell: ceph orch apply osd --all-available-devices
      delegate_to: manager-01
      run_once: true

    - name: Create volume named "shared"
      shell: ceph fs volume create shared
      delegate_to: manager-01
      run_once: true
