---
- hosts: all
  become: true

  name: Install CEPH binaries
  tasks:
    - name: Add CEPH base repository
      ansible.builtin.yum_repository:
        name: ceph
        description: CEPH base
        baseurl: https://download.ceph.com/rpm-quincy/el8/$basearch
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add CEPH noarch repository
      ansible.builtin.yum_repository:
        name: ceph-noarch
        description: CEPH noarch
        baseurl: https://download.ceph.com/rpm-quincy/el8/noarch
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add CEPH source repository
      ansible.builtin.yum_repository:
        name: ceph-source
        description: CEPH SRPMS
        baseurl: https://download.ceph.com/rpm-quincy/el8/SRPMS
        file: ceph
        gpgkey: https://download.ceph.com/keys/release.asc
        gpgcheck: true
        enabled: true

    - name: Add EPEL repository
      ansible.builtin.dnf:
        name:
          - epel-release
        state: present

    - name: Install CEPH and dependencies
      ansible.builtin.dnf:
        name:
          - cephadm
          - ceph-common
        state: present

- hosts: all
  become: true

  name: Initialise CEPH cluster
  tasks:
    - name: Check for existing config file
      stat:
        path: /etc/ceph/ceph.conf
      register: ceph_conf

    - name: Bootstap the cluster
      ansible.builtin.shell: cephadm bootstrap --mon-ip 10.0.0.1 --ssh-user ansible --skip-dashboard --skip-monitoring-stack --skip-firewalld
      delegate_to: manager-01
      run_once: true
      when: not ceph_conf.stat.exists

    - name: Get public key contents
      ansible.builtin.shell: cat /etc/ceph/ceph.pub
      register: ceph_pub
      delegate_to: manager-01
      run_once: true

    - name: Distribute the public key to all hosts
      ansible.builtin.lineinfile:
        path: /home/ansible/.ssh/authorized_keys
        line: "{{ ceph_pub.stdout }}"

    - name: Add manager-02 to the cluster
      shell: ceph orch host add manager-02 10.0.0.2 --labels _admin
      delegate_to: manager-01
      run_once: true

    - name: Add manager-03 to the cluster
      shell: ceph orch host add manager-03 10.0.0.3 --labels _admin
      delegate_to: manager-01
      run_once: true

    - name: Add all available disks to the cluster
      shell: ceph orch apply osd --all-available-devices
      delegate_to: manager-01
      run_once: true

- hosts: all
  become: true

  name: Block CEPH traffic in the public zone
  tasks:
    - name: Disable ceph traffic in the public zone
      ansible.posix.firewalld:
        service: ceph
        permanent: true
        state: disabled
        immediate: true

    - name: Disable ceph-mon traffic in the public zone
      ansible.posix.firewalld:
        service: ceph-mon
        permanent: true
        state: disabled
        immediate: true

    - name: Disable 9283/tcp traffic in the public zone
      ansible.posix.firewalld:
        port: 9283/tcp
        permanent: true
        state: disabled
        immediate: true

    # - name: Create a "/mnt/shared" directory if it does not exist
    #   ansible.builtin.file:
    #     path: /mnt/shared
    #     state: directory
    #     mode: '0755'

- hosts: all
  become: true

  name: Create and mount a CEPH volume named "shared"
  tasks:
    - name: Create the volume
      shell: ceph fs volume create shared
      delegate_to: manager-01
      run_once: true

    - name: Wait for the volume to become available
      shell: ceph health
      register: result
      until: result.stdout == "HEALTH_OK"
      retries: 30
      delay: 10

    - name: Mount the new volume to /mnt/shared
      ansible.posix.mount:
        src: admin@.shared=/
        path: /mnt/shared
        opts: mon_addr=10.0.0.1:6789,noatime,_netdev
        state: mounted
        fstype: ceph
