---
- hosts: all
  become: true

  name: DNF package upgrades
  tasks:
    - name: Upgrade all except Docker packages to latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
        allowerasing: true
        nobest: true
        exclude:
          - docker-*
          - containerd.io
